### ISSUE TITLE
check redirects

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/check#43]
```
$ check urls https://some.site/ | tee sitemap.txt | check redirects > redirect.txt
```

**Comment by kamilsk** [comment]
redirect rules:

```yaml
- name: Let's Encrypt configured right for OctoLab
  rules:
  - name: http:// -> https://www
     start: http://octolab.org/
     end: https://www.octolab.org/
etc.
```
